swagger: "2.0"
info:
  title: Meta Framework API
  description: Meta Framework API
  version: 1.0.0
host: meta-framework-gateway-3s4mrx1z.ew.gateway.dev
schemes:
  - https
produces:
  - application/json
security:
  - api_key: []
#securityDefinitions:
#  api_key:
#    type: apiKey
#    name: key
#    in: query
paths:
  /astro:
      get:
        x-google-backend:
          address: https://astro-app-wlyiet7xva-ew.a.run.app/
          path_translation: CONSTANT_ADDRESS
        summary: Get Astro
        operationId: getAstro
        responses:
          '200':
            description: A successful response
  /{page}:
    get:
      x-google-backend:
        address: https://{page}-app-wlyiet7xva-ew.a.run.app/{page}
        path_translation: CONSTANT_ADDRESS
      summary: Get Astro
      operationId: getAstro
      responses:
        '200':
          description: A successful response
      parameters:
        - name: page
          in: path
          description: Page
          required: true
          type: string
